---
apiVersion: v1
kind: Service
metadata:
  namespace: draw-app
  name: draw-app-${INSTANCE_NAME}
  labels:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  selector:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
  ports:
    - protocol: TCP
      name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: draw-app
  name: draw-app-${INSTANCE_NAME}
  labels:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: draw-app
      app.kubernetes.io/instance: ${INSTANCE_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: draw-app
        app.kubernetes.io/instance: ${INSTANCE_NAME}
    spec:
      containers:
        - name: draw-app
          image: ${GCP_REGISTRY}/draw-app:${VERSION}
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  namespace: draw-app
  name: draw-app-${INSTANCE_NAME}
  labels:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  entryPoints:
    - https
  routes:
    - match: Host(`${INSTANCE_NAME}.draw-app.gcp.app.com`)
      kind: Rule
      services:
        - namespace: draw-app
          name: draw-app-${INSTANCE_NAME}
          port: 8080
  tls:
    certResolver: letsencrypt
    domains:
      - main: "*.draw-app.gcp.app.com"