---
apiVersion: v1
kind: Service
metadata:
  namespace: draw-app
  name: draw-app-${INSTANCE_NAME}
  labels:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  selector:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
  ports:
    - protocol: TCP
      name: http
      port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: draw-app
  name: draw-app-${INSTANCE_NAME}
  labels:
    app.kubernetes.io/name: draw-app
    app.kubernetes.io/instance: ${INSTANCE_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: draw-app
      app.kubernetes.io/instance: ${INSTANCE_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: draw-app
        app.kubernetes.io/instance: ${INSTANCE_NAME}
    spec:
      containers:
        - name: draw-app
          image: ${GCP_REGISTRY}/draw-app:${VERSION}
          ports:
            - name: http
              containerPort: 80