---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "drawapp"
  namespace: "default"
  labels:
    app: "drawapp"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "drawapp"
  template:
    metadata:
      labels:
        app: "drawapp"
    spec:
      containers:
      - name: "drawapp-sha256-1"
        image: "eu.gcr.io/teraform-1-319109/draw-app@sha256:2fefdfa748e9d4e4ff2e7e3e369f016713b214364e45ad099505ad311d9694a2"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "drawapp-service"
  namespace: "default"
  labels:
    app: "drawapp"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "drawapp"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80