version: 2

jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
     - checkout
     - setup_remote_docker:
        version: 20.10.6
     - run: 
        name: Push new image
        command: |
          TAG=${CIRCLE_SHA1::7}
          docker build -f Dockerfile -t eu.gcr.io/${GOOGLE_PROJECT_ID}/draw-app:${TAG} $@ .
          echo "$JSON_64" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
          docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/draw-app:${TAG}

  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          DEPLOYMENT_NAME: app
          DEPLOYMENT_CONTAINER_NAME: draw-app
    steps:
      - setup_remote_docker
      - run: 
          name: Deploy application to Google Kubernetes Engine
          command: |
            TAG=${CIRCLE_SHA1::7}

            echo $JSON_64 | base64 --d > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json

            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

      - run:
          name: Deploy to GKE
          command: |
            kubectl apply -f app.yaml
            kubectl set image deployment/$DEPLOYMENT_CONTAINER_NAME $DEPLOYMENT_CONTAINER_NAME=eu.gcr.io/${GOOGLE_PROJECT_ID}/$DEPLOYMENT_CONTAINER_NAME:$TAG
workflows: 
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
           - GCLOUD
          filters:
           branches:
             only: main
      - deploy:
          context:
           - GCLOUD
          requires:
           - build
          filters:
           branches:
             only: main