version: 2

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
     - checkout
     - setup_remote_docker
     - run: 
        name: Build image
        command: |
          TAG=${CIRCLE_SHA1::7}
          docker build -f Dockerfile -t eu.gcr.io/teraform-1-319109/draw-app:$TAG $@ .
          echo "$JSON_64" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
          docker push eu.gcr.io/teraform-1-319109/draw-app:$TAG

  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          DEPLOYMENT_NAME: draw-app
          DEPLOYMENT_CONTAINER_NAME: draw-app
    steps:
      - setup_remote_docker
      - run: 
          name: Deploy application to Google Kubernetes Engine
          command: |
            TAG=${CIRCLE_SHA1::7}

            echo $JSON_64 | base64 --d > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json

            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            
            gcloud container clusters get-credentials circleci
            kubectl set image deployment/circle-ci-cluster $DEPLOYMENT_CONTAINER_NAME=eu.gcr.io/teraform-1-319109/$DEPLOYMENT_NAME:$TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
           - GCLOUD
          filters:
           branches:
             only: main
      - deploy:
          context:
           - GCLOUD
          requires:
           - build
          filters:
           branches:
             only: main