version: 2.1
jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
     - checkout
     - run: 
        name: Build image
        command: |
          docker build -t webbb .
          docker save webbb:latest | gzip > webbb_latest.tar.gz
  push:
    docker:
      - image: google/cloud-sdk
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - run: 
          name: Deploy 
          command: |
            echo ${GCLOUD_SERVICE_KEY} > keyfile.json
            gcloud auth activate-service-account --key-file=keyfile.json
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            gcloud --quiet app deploy
workflows:
  version: 2.1
  build_and_push:
    jobs:
      - build:
          context:
            - docker
          filters:
           branches:
             only: master
      - push:
          context:
           - GCLOUD
          requires:
           - build