version: 2.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: google/cloud-sdk:latest
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
     - checkout
     - run: 
        name: Build image
        command: |
          docker build -t webbb .
          docker save webbb:latest | gzip > webbb_latest.tar.gz
  push:
    docker:
      - image: google/cloud-sdk:latest
        auth:
          username: _json_key
          password: $DOCKER_PASSWORD
    steps:
      - run: 
          name: GCP auth
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > keyfile.json
            gcloud auth activate-service-account --key-file keyfile.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
            - docker
          filters:
           branches:
             only: main
      - push:
          context:
           - GCLOUD
          requires:
           - build