version: 2

jobs:
  build:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
     - checkout
     - setup_remote_docker:
        version: 20.10.6
     - run: 
        name: Build image
        command: |
          TAG=${CIRCLE_SHA1::7}
          docker build -t draw-app:$TAG -f ./Dockerfile .

  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          DEPLOYMENT_NAME: draw-app
          DEPLOYMENT_CONTAINER_NAME: draw-app
    steps:
      - setup_remote_docker
      - run: 
          name: Deploy application to Google Kubernetes Engine
          command: |
            TAG=${CIRCLE_SHA1::7}

            cat $JSON_64 | base64 --d > gcloud-service-key.json
            gcloud auth activate-service-account --key-file=gcloud-service-key.json

            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE

            docker build -t draw-app:$TAG -f ./Dockerfile .
            docker tag draw-app:$TAG eu.gcr.io/${GOOGLE_PROJECT_ID}/draw-app:${CIRCLE_SHA1}
            gcloud docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/draw-app:${CIRCLE_SHA1}
            gcloud docker -- push eu.gcr.io/${GOOGLE_PROJECT_ID}/draw-app:${CIRCLE_SHA1}


workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          context:
           - GCLOUD
          filters:
           branches:
             only: main
      - deploy:
          context:
           - GCLOUD
          requires:
           - build
          filters:
           branches:
             only: main