---
apiVersion: "v1"
kind: "Namespace"
metadata:
  name: "myapp"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "draw-app"
  namespace: "myapp"
  labels:
    app: "draw-app"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "draw-app"
  template:
    metadata:
      labels:
        app: "draw-app"
    spec:
      containers:
      - name: "draw-app-1"
        image: "eu.gcr.io/teraform-1-319109/draw-app:057c674"