apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "draw-app-hpa-u9dc"
  namespace: "myapp"
  labels:
    app: "draw-app"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "draw-app"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80